language: generic
sudo: false
cache:
  directories:
    - /tmp/calibre-installer-cache

env:
  global:
    - PATH=$HOME/calibre:$HOME/bin:$PATH
    - GEN_EPUB_BOOK_VERSION=v0.3.1

before_install:
  - openssl aes-256-cbc -K $encrypted_081938a76f01_key -iv $encrypted_081938a76f01_iv -in gh_rsa.enc -out gh_rsa -d

install:
  - curl -SL https://download.calibre-ebook.com/linux-installer.py | python -c "import sys; import os; main=lambda x:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main(os.getenv('HOME'))"
  - ebook-convert --version
  -
  - mkdir -p "$HOME/bin"
  - curl -SL "https://github.com/nabijaczleweli/gen-epub-book.rs/releases/download/$GEN_EPUB_BOOK_VERSION/gen-epub-book.rs-$GEN_EPUB_BOOK_VERSION" -o "$HOME/bin/gen-epub-book"
  - chmod +x "$HOME/bin/gen-epub-book"

script:
  - make OUTDIR="../kaschism/"

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then
      (
        echo "Update kaschism for commits $TRAVIS_COMMIT_RANGE";
        echo;
        git log "$TRAVIS_COMMIT_RANGE" --pretty=oneline 2>/dev/null || echo "$TRAVIS_COMMIT_MESSAGE";
      ) > $TRAVIS_BUILD_DIR/../DOC_UPDATE_MSG;
      mkdir -p ~/.ssh && cp gh_rsa ~/.ssh/id_rsa && chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa;
      git clone -b master "git@github.com:nabijaczleweli/nabijaczleweli.github.io.git" "$TRAVIS_BUILD_DIR-webpage";
      mkdir -p "$TRAVIS_BUILD_DIR-webpage/kaschism";
      pushd "$TRAVIS_BUILD_DIR-webpage/";
      rm -rf kaschism/;
      mv ../kaschism/ .;
      git config --global user.email "nabijaczleweli@gmail.com";
      git config --global user.name "Nabijaczleweli Autouploader Bot";
      git config --global push.default simple;
      git add .;
      git commit -F ../DOC_UPDATE_MSG;
      git push;
      popd;
    fi
